"""Init

Revision ID: 46de16d4d6a8
Revises: b063284ff4d3
Create Date: 2024-01-21 00:09:03.669694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46de16d4d6a8'
down_revision: Union[str, None] = 'b063284ff4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_contact_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_contact_id_fkey', 'users', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
