"""Init

Revision ID: b063284ff4d3
Revises: c2537fa26651
Create Date: 2024-01-21 00:05:44.718379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b063284ff4d3'
down_revision: Union[str, None] = 'c2537fa26651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contact_id')
    # ### end Alembic commands ###
